---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: subject
  application:
    name: lab-4-subject
server:
  port: 9000
words: I,You,He,She,It

---
spring:
  profiles: verb
  application:
    name: lab-4-verb
server:
  port: 9001
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
  application:
    name: lab-4-article
server:
  port: 9002
words: a,the

---
spring:
  profiles: adjective
  application:
    name: lab-4-adjective
server:
  port: 9003
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
  aplication:
    name: lab-4-noun
server:
  port: 9004
words: boat,book,vote,seat,backpack,partition,groundhog  
