---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
      
---
spring:
  profiles: sentence
  application:
    name: lab-4-sentence
    
---
spring:
  profiles: subject
  application:
    name: lab-4-subject
  
---
spring:
  profiles: verb
  application:
    name: lab-4-verb

---
spring:
  profiles: article
  application:
    name: lab-4-article

---
spring:
  profiles: adjective
  application:
    name: lab-4-adjective

---
spring:
  profiles: noun
  application:
    name: lab-4-noun
    
